@serverUrl = http://localhost:3000/api
###

POST {{serverUrl}}/employee
Content-Type: application/json

{
    "name": "User3", 
    "phone": "0995094072", 
    "email":"user3@yahoo.com", 
    "sex": 0, 
    "avatar":"https://res.cloudinary.com/v-webdev/image/upload/v1658635301/v-media/profile-user_vglyvp.png"
}

###

GET {{serverUrl}}/employee

###

GET {{serverUrl}}/employee/7
###

PUT {{serverUrl}}/employee/7
Content-Type: application/json

{
    "name": "User7", 
    "phone": "0995094072", 
    "email":"user7@yahoo.com", 
    "sex": "1", 
    "avatar":"https://res.cloudinary.com/v-webdev/image/upload/v1658635301/v-media/profile-user_vglyvp.png"
}

###D
DELETE  {{serverUrl}}/employee/7
Content-Type: application/json
###
GET {{serverUrl}}/department
###

POST {{serverUrl}}/department
Content-Type: application/json

{
    "name": "Accounting department", 
    "code": "04-Dep"
}
###

PUT {{serverUrl}}/department/4
Content-Type: application/json

{
    "name": "Audit department", 
    "code": "04-Dep"
}

###

POST {{serverUrl}}/dep-emp
Content-Type: application/json

{
    "departmentId": 4, 
    "employeeId": 6
}

###
GET {{serverUrl}}/dep-emp
###

DELETE {{serverUrl}}/dep-emp/8
###